<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Tessel.Gallery</RootNamespace>
    <AssemblyName>Tessel.Gallery</AssemblyName>
    <ApplicationIcon>Resources\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tessel.UI\Tessel.UI.csproj" />
  </ItemGroup>

</Project>
